name: GaussianEditor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  # for pytorch and support custom C++ extensions
  - cuda-nvcc=11.8*
  - cuda-libraries-dev=11.8*
  - pytorch=2.1.0=py3.8_cuda11.8*
  - torchvision=0.16.0=py38_cu118
  # for triton
  - lit=17.0.6
  - cmake=3.27.9
  # for faster setup.up building?
  - ninja=1.11.1
  - pip:
    - -r requirements.lock.txt